In [1]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [2]:
env = gym.make("FrozenLake-v0")

In [3]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))

In [8]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.7
discount_rate = 0.85

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [9]:
rewards_all_episodes = []

In [10]:
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward 
        if done == True: 
            break
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)


********Average reward per thousand episodes********

1000 :  0.2680000000000002
2000 :  0.4040000000000003
3000 :  0.35900000000000026
4000 :  0.3830000000000003
5000 :  0.3990000000000003
6000 :  0.3740000000000003
7000 :  0.4080000000000003
8000 :  0.3880000000000003
9000 :  0.4220000000000003
10000 :  0.36800000000000027


********Q-table********

[[1.89541112e-03 1.81635416e-03 5.83502439e-02 1.52719372e-02]
 [3.28565980e-05 8.53328286e-05 4.85781687e-04 1.43581648e-02]
 [8.90662264e-03 2.39975028e-03 5.41030220e-03 3.98456003e-04]
 [1.09312356e-04 1.12031588e-04 1.22944935e-04 1.17159293e-02]
 [2.06940280e-02 1.34552149e-02 6.99392555e-04 4.27708185e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.44190818e-03 4.16048998e-06 1.20690860e-02 1.51315919e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [4.11822290e-03 7.58792377e-03 7.02150075e-03 3.83867290e-02]
 [1.15223130e-03 6.87302394e-02 3.59366464e-02 3.19240469e-02]
 [3.10604870e-01

In [11]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    for step in range(max_steps_per_episode):        
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state
env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
